# ============================================
# Contour Deep - Retrieval Network Training Config
# ============================================

# 模型配置
model:
  output_dim: 128  # 特征维度

# 数据配置
data:
  num_negatives: 10  # 每个anchor的负样本数量
  max_cache_size: 500  # 内存缓存大小（LRU）

# 优化器配置
optimizer:
  optimizer: adamw
  learning_rate: 0.0001  # 1e-4
  weight_decay: 0.0001  # 1e-4
  # 如果用SGD
  momentum: 0.9

# 学习率调度配置
scheduler:
  scheduler: cosine  # cosine, step, none
  warmup_epochs: 5  # Warmup轮数
  # 如果用StepLR
  step_size: 10
  gamma: 0.1

# 损失函数配置
loss:
  loss: triplet  # triplet, infonce
  # Triplet Loss参数
  margin: 0.5
  mining: hard  # hard, semi-hard, all
  # InfoNCE Loss参数
  temperature: 0.07

# 训练配置
training:
  num_epochs: 50
  batch_size: 4
  num_workers: 4
  save_freq: 5  # 每N个epoch保存一次checkpoint

# 日志配置
logging:
  log_dir: logs
  checkpoint_dir: checkpoints
  use_tensorboard: true
